# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [40]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import warnings

# Import API key
from api_keys import g_key

#filter out warnings
warnings.filterwarnings('ignore')

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [43]:
gcity_df = pd.read_csv("../WeatherPy/output_data/cities.csv")
gcity_df.head()
gcity_df.dtypes
gcity_df["Humidity"].max()

100

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [6]:
gmaps.configure(api_key=g_key)

In [45]:
# Store latitude and longitude in locations
locations = gcity_df[["Lat", "Lng"]]

#add Humidity as weight
weight = gcity_df["Humidity"]

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=weight, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [38]:
#use df.loc and criteria from instructions to get perfect vacation spots
hotel_df = gcity_df.loc[(gcity_df["Max Temp"]<80) & (gcity_df["Max Temp"]>70) & (gcity_df["Wind Speed"]<10)
                        & (gcity_df["Cloudiness"]==0)]
hotel_df.head(10)

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
2,rikitea,0,PF,1569382354,65,-23.12,-134.97,71.09,3.18
195,biak,0,ID,1569382377,46,-0.91,122.88,75.95,6.42
268,iquitos,0,PE,1569382386,94,-3.75,-73.25,73.40,1.12
283,xuanhua,0,CN,1569382388,29,40.61,115.04,73.25,2.24
299,riyadh,0,SA,1569382389,27,24.63,46.72,77.00,4.70
348,upata,0,VE,1569382395,90,8.02,-62.41,71.63,3.69
355,behbahan,0,IR,1569382396,25,30.59,50.24,77.00,3.40
416,jalu,0,LY,1569382403,29,29.03,21.55,77.93,8.86
497,nizwa,0,OM,1569382413,71,22.93,57.53,71.81,3.58
502,buraydah,0,SA,1569382414,40,26.33,43.97,73.40,2.24

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [42]:
hotel_df["Hotel Name"] = ""
hotel_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
2,rikitea,0,PF,1569382354,65,-23.12,-134.97,71.09,3.18,
195,biak,0,ID,1569382377,46,-0.91,122.88,75.95,6.42,
268,iquitos,0,PE,1569382386,94,-3.75,-73.25,73.40,1.12,
283,xuanhua,0,CN,1569382388,29,40.61,115.04,73.25,2.24,
299,riyadh,0,SA,1569382389,27,24.63,46.72,77.00,4.70,

In [ ]:
# find the closest restaurant of each type to coordinates

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    
    "rankby": "distance",
    "type": "hotels",
    "radius": 5000
    "key": g_key,
}
# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():

   

    # assemble url and make API request
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest {restr_type} restaurant is {results[0]['name']}.")
        
        types_df.loc[index, 'name'] = results[0]['name']
        types_df.loc[index, 'address'] = results[0]['vicinity']
        types_df.loc[index, 'price_level'] = results[0]['price_level']
        types_df.loc[index, 'rating'] = results[0]['rating']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display Map